# Generated by Django 4.2.7 on 2024-05-15 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('encrypted_password', models.CharField(max_length=120)),
                ('birthdate', models.DateField()),
                ('token', models.CharField(max_length=50, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CocheFavorito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carbuyrest22app.coche')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carbuyrest22app.user')),
            ],
        ),
        migrations.AddField(
            model_name='coche',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carbuyrest22app.user'),
        ),
    ]
