# Generated by Django 4.2.7 on 2024-06-01 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carbuyrest22app', '0002_rename_coche_car_rename_cochefavorito_favouritecar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='image_url',
            field=models.URLField(default='https://shorturl.at/YJLnZ'),
        ),
    ]
